#!/bin/bash

sleep 60
ssh -i /home/reader/.ssh/dns.id_ed25519 root@192.168.1.50 "tcpdump -n -i pflog0 -s 1500 -w-" | tee >(tshark -l -s 1500 -N n -r- -T ek | socat -u - udp-datagram:127.0.0.1:22055) | tshark -l -s 1500 -N n -r- -T ek -e ip.dst -e dns.qry.name -e dns.resp.name -e dns.resp.type -e dns.a -e dns.cname -e dns.soa.mname -e dns.soa.rname -e dns.aaaa -e dns.mx.mail_exchange -e dns.txt | socat -u - udp-datagram:127.0.0.1:3111
